sudo: required
services:
  - docker

before_install:
  - docker build -t smoters/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true smoters/react-test npm run test

after_success:
  - docker build -t smoters/multi-client ./client
  - docker build -t smoters/multi-nginx ./nginx
  - docker build -t smoters/multi-server ./server
  - docker build -t smoters/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push smoters/multi-client
  - docker push smoters/multi-nginx
  - docker push smoters/multi-server
  - docker push smoters/multi-worker
    

